server:
  port: 9005
spring:
  application:
    name: carkeeper-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.129:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/carkeeper_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
#  main:
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.user.pojos

#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
#        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
#        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          #如果enabled设置为false，则请求超时交给ribbon控制
#          enabled: true
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            # 熔断器超时时间，默认：1000/毫秒
#            timeoutInMilliseconds: 20000
