server:
  port: 9003
spring:
  application:
    name: carkeeper-shop
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.129:8848
    alibaba:
      seata:
        tx-service-group: carkeeper_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carkeeper_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  kafka:
    bootstrap-servers: 192.168.200.129:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #        排除datasource 自动化配置的方式 1
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.shop.pojos

#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
#        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
#        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          #如果enabled设置为false，则请求超时交给ribbon控制
#          enabled: true
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            # 熔断器超时时间，默认：1000/毫秒
#            timeoutInMilliseconds: 20000

file:
  oss:
    bucket-name: jasonmotcrlleadnews
    access-key-id: LTAI4G9SLvwMoT9obMXn7BkR
    access-key-secret: JcniBfcfT6pSsuQnCOXN3EWI8KZVt8
    endpoint: oss-cn-shanghai.aliyuncs.com
    web-site: https://jasonmotcrlleadnews.oss-cn-shanghai.aliyuncs.com/
    proxy-username: aliyun-sdk-java
    socket-timeout: 10000
    idle-connection-time: 10000
    connection-request-timeout: 4000
    max-connections: 2048
    max-error-retry: 5
    white-list: 127.0.0.1
    connection-timeout: 10000
    profix: material

xxljob:
  admin:
    addresses: http://192.168.200.129:8888/xxl-job-admin
  executor:
    appname: carkeeper-shop
    port: 9999
    logPath: D:/logs/xxl-job